### PR TITLE
add setup.py via setuptools

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by inducer** [comment]
In the situations where I use compyte (pycuda, pyopencl, loopy), it gets included as a git submodule rather than installed as a separate package, so what you're proposing somewhat defeats my way of using the package (so far). What makes you want to have the package separately installable?

**Comment by ignatenkobrain** [comment]
Yes, I'm packaging pyopencl for Fedora. But I can't package submodules if its separate projects.

**Comment by inducer** [comment]
Sorry for the stupid question, but why not? Same authors, same license--what's the issue?

**Comment by ignatenkobrain** [comment]
Problem is that it's separate project used by multiple other projects (pycuda, pyopncl, ...) and I should package it separately.

**Comment by inducer** [comment]
Sorry, not interested. Compyte, to me, is not a separate project. The repository is a way for me to share some files between PyCUDA and PyOpenCL. It's deeply integrated into both, and it doesn't have (or want) its own version number. If I just stuck the same files into both projects by hand, I'm guessing we wouldn't be having this conversation. I'd suggest you treat the files as that.

Relatedly, it seems Fedora is having second thoughts on a related subject at a larger scale: https://lwn.net/Articles/660429/

**Pull request closed without merging**
